[package]
name = "pubky-desktop-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33"
egui = "0.33"
pubky = "0.6.0-rc.6"
qrcode = "0.14"
image = "0.25"
tokio = { version = "1", features = ["full"] }
